from .recognize_past_conjugation import recognize_past_conjugation
from .recognize_passive_past_continuous_conjugation import recognize_passive_past_continuous_conjugation
from .recognize_active_non_past_conjugation import recognize_active_non_past_conjugation
from .recognize_passive_present_continuous_conjugation import recognize_passive_present_continuous_conjugation
