from .all.persons.create_all_subjunctive_personal_forms import create_all_subjunctive_personal_forms
from .all.persons.create_all_present_personal_forms import create_all_present_personal_forms
from .all.persons.create_all_past_personal_forms import create_all_past_personal_forms
